site_name: Hulu's Blog
site_description: Not when I came to die, discover that I had not lived
site_author: ZhengQiaoyu

theme:
  name: material
  font: false
  #logo: logo.png
  #favicon: logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.expand
    - navigation.footer
    - toc.follow
    - navigation.top
    - serach.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: slate
      primary: deep purple
      accent: purple  

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zqy10
    - icon: fontawesome/solid/paper-plane
      link: mailto:<3230100228@zju.edu.cn>
    - icon: fontawesome/brands/qq
      link: mailto:<3508743071@qq.com>

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css

markdown_extensions:
  - meta
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

copyright: 
  Copyright &copy; 2024 <a href="https://github.com/zqy10" target="_blank" rel="noopener">Hulu ZQY</a>

repo_url: https://github.com/zqy10/hulublog
repo_name: zqy10/hulublog